name: Firebase Firestore CI/CD
on:
  push:
    paths:
      - 'firestore.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Use firebase-tools
      run: npm -g i yarn firebase-tools

    - name: Deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_TAMURO_TEST01 }}
      working-directory: ${{ github.workspace }}
      run: firebase deploy --only firestore --token "$FIREBASE_TOKEN"
