name: Firebase CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm -g i yarn
    - name: Install Packages of UI
      run: yarn
    - name: Build UI
      run: yarn build
