name: Firebase CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm -g i yarn firebase-tools
    - name: Install Packages of functions
      working-directory: $GITHUB_WORKSPACE/functions
      run: yarn
    - name: Install Packages of UI
      run: yarn
    - name: Set Firebase API Key
      env:
        API_KEY: ${{ secrets.API_KEY_TAMURO_TEST01 }}
      working-directory: $GITHUB_WORKSPACE
      run: echo "export default '$API_KEY'" > src/plugins/firebase-api-key.js
    - name: UI version
      working-directory: $GITHUB_WORKSPACE
      run: echo "export default '`git rev-parse --short HEAD`'" > src/store/version.js
    - name: Build UI
      working-directory: $GITHUB_WORKSPACE
      run: yarn build
    - name: Deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_TAMURO_TEST01 }}
      working-directory: $GITHUB_WORKSPACE
      run: firebase deploy --token "$FIREBASE_TOKEN"
