name: Firebase UI CI/CD
on:
  push:
    paths-ignore:
    - 'functions/**'
    - 'firestore.*'
    - 'storage.rules'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-ui-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-ui-cache
      with:
        path: ${{ steps.yarn-ui-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-ui-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-ui-

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Use yarn
      run: npm -g i yarn

    - name: Install dependencies
      working-directory: ${{ github.workspace }}
      run: yarn --frozen-lockfile

    - name: Set Firebase API Key
      env:
        API_KEY: ${{ secrets.API_KEY_TAMURO_TEST01 }}
      run: echo "export default '$API_KEY'" > src/plugins/firebase-api-key.js

    - name: Set version to UI
      run: echo "export default '`git rev-parse --short HEAD`'" > src/conf/version.js

    - name: Build UI
      run: yarn build

    - name: Set version to Hosting
      run: echo "{\"version\":\"`git rev-parse --short HEAD`\"}" > dist/version.json

    - name: Deploy UI
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_TAMURO_TEST01 }}
      working-directory: ${{ github.workspace }}
      run: yarn deploy --only hosting --token "$FIREBASE_TOKEN"

    - name: Set version to DB
      run: curl https://us-central1-tamuro-test01.cloudfunctions.net/api/updateServiceVersion\?key\=$API_KEY
