name: Firebase CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm -g i yarn firebase-tools
    - name: Install Packages of UI
      run: yarn
    - name: Set Firebase API Key
      env:
        API_KEY: ${{ secrets.API_KEY_TAMURO_TEST01 }}
      working-directory: ${{ github.workspace }}
      run: echo "export default '$API_KEY'" > src/plugins/firebase-api-key.js
    - name: UI version
      working-directory: ${{ github.workspace }}
      run: echo "export default '`git rev-parse --short HEAD`'" > src/store/version.js
    - name: Build UI
      working-directory: ${{ github.workspace }}
      run: yarn build
